### ISSUE TITLE
Installation with pip fails

### ISSUE THREAD

**Issue by nbeliy** [Gilles86/pymp2rage#3]
Installation using pip fails due to syntax error in `mp2rage/version.py`:

```
python3 -m pip install git+https://github.com/Gilles86/pymp2rage
Collecting git+https://github.com/Gilles86/pymp2rage
  Cloning https://github.com/Gilles86/pymp2rage to /tmp/pip-40es0w05-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-40es0w05-build/setup.py", line 8, in <module>
        exec(f.read())
      File "<string>", line 23
        "License :: OSI Approved :: Apache License, 2.0"",
                                                         ^
    SyntaxError: EOL while scanning string literal
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-40es0w05-build/
```

**Comment by gjheij** [comment]
Hi! If this has prevented you from using the package, you can run `git clone https://github.com/Gilles86/pymp2rage.git` to clone the repo and change line 23 `"License :: OSI Approved :: Apache License, 2.0""` to `"License :: OSI Approved :: Apache License, 2.0"` and line 47 `LICENSE = "Apache License, 2.0""` to `LICENSE = "Apache License, 2.0"` in the `pymp2rage/version.py` file, then run `python setup.py develop` from within the cloned repo directory. That should do it.

**Comment by nbeliy** [comment]
Sorry for the late response, I've missed a notification.

Yes, it easy to fix, the issue was just to signal it.

**Comment by mckeuken** [comment]
I created a pull request with the suggested changes
